### PR TITLE
Update /projetcs/directory

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

Rebuild the [projects directory](https://canonical-com-909.demos.haus/projects/directory) accordign to the new design.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- QA according to the design. I batch-changed all the rows, there could be some errors, please check the content.
- @juanruitina - Claudio Gomboli and possibly other people who are no longer at Canonical are listed on that page. Who's the best person to revise the content?

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-3809

## Screenshots

image

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
> * Can you add the breadcrumbs, as per the mockup?

@juanruitina  What is the link to the parent? It currently says "open source", not sure which page that is. Will set to the products page for now.

**Comment by juanruitina** [comment]
For breadcrumbs you can do "[Projects](/projects) > Directory". Other than that, this LGTM, feel free to add UX+1 when you tweak that.

FYI, @anthonydillon will inquire about the content.

**Comment by lyubomir-popov** [comment]
@ClementChaumel this is ok UX and UI wise, we just need code/QA please.

**Review by ClementChaumel — APPROVED** [review]
Good job 🎉

**Pull request merged**
