### PR TITLE
Add Software Partner Programme

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Add /partners/software page
- Add partners to partners.ubuntu.com
- Add filter to /partners/find-a-partner page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: 
    - http://0.0.0.0:8002/partners/software
    - http://0.0.0.0:8002/partners/find-a-partner?filters=software
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

## Issue / Card

Fixes [#3893](https://github.com/canonical-web-and-design/web-squad/issues/3893)

### CODE REVIEW

**Comment by anasereijo** [comment]
@pmahnke LGTM 👍

**Comment by SirSamTumless** [comment]
@solazio Are you fine to give this a quick review?

**Comment by solazio** [comment]
@pmahnke can you please fix the failing actions.

**Comment by pmahnke** [comment]
@solazio I have spent 2 hours looking at this and can't find the error.  `dotrun test` is happy.  You have any ideas?

**Comment by solazio** [comment]
> @solazio I have spent 2 hours looking at this and can't find the error. `dotrun test` is happy. You have any ideas?

@pmahnke I fixed the tests, but please do another QA.

**Pull request closed without merging**
