### PR TITLE
Optimise suru image and avoid layout shift

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- switch dark suru image for an optimised one
- add aspect ratio rule to avoid layout shift at load time

## QA

- check

## Issue / Card

Fixes WD-5087

### CODE REVIEW

**Comment by mtruj013** [comment]
@lyubomir-popov demo here: https://canonical-com-956.demos.haus/

**Review by mtruj013 — COMMENTED** [review]
LGTM

**Review by mtruj013 — APPROVED** [review]

**Comment by lyubomir-popov** [comment]
ooks good

**Review by anthonydillon — APPROVED** [review]
Interesting, I have not used `aspect-ratio` before. Read up on it this looks good and relatively [well-supported](https://caniuse.com/?search=aspect-ratio).

**Pull request merged**
