### PR TITLE
feat: /data/kafka/support build

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Built page as per [doc](https://docs.google.com/document/d/1eM-xPqx1CtoxSg4aOHlY3QRPu5L3o-jQPkc_q1CAr10/edit?tab=t.0) and [design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=2124-29581&node-type=frame&m=dev)

## QA

- View the site locally in your web browser at: https://canonical-com-1411.demos.haus/data/kafka/support
- Check against doc and design 

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-15042

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
just one comment on this - can we do the same aspect ratio change I mentioned in the spark pr? so on small/medium screens the images become 3x2

**Comment by mtruj013** [comment]
@lyubomir-popov done!

**Comment by eliman11** [comment]
Everything looks good to me! Just one quick change - could you add 'our' to the heading as per @Sophie-32's comment on the copydoc to the 'What customers say' heading? Feel free to add UX+1 after the change, thanks!

**Review by samhotep — APPROVED** [review]
LGTM!

**Pull request merged**
