### PR TITLE
Update copy & include video on /application

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

**This PR addresses 2 issues**
- Update copy based on [copydoc](https://docs.google.com/document/d/1RZXj-LH_7Eg-pWJR9tE_V3D5CSDzCzyhyn0WoHLZwpQ/edit#heading=h.pmojv69jw2s7)
- Add 'How we hire at Canonical' video, see [issue](https://github.com/canonical/canonical.com/issues/649)

## QA

- Go to /careers/application
- Check the application matches the copydoc
- Check the video is correct and loads

## Issue / Card

Fixes https://github.com/canonical/canonical.com/issues/649
https://github.com/canonical/canonical.com/issues/642

### CODE REVIEW

**Review by minkyngkm — COMMENTED** [review]
1. Need a space after "of" 
image

2. Do we need to add a thumbnail for the video?
image

**Comment by petesfrench** [comment]
@minkyngkm It is working on my end, can you try a hard refresh? 
image

**Review by minkyngkm — APPROVED** [review]
We might need to make issues for the things I commented...!  but including Mark's video looks good in this PR.

**Comment by petesfrench** [comment]
I have created new issues for the other comments: 
https://github.com/canonical/ubuntu.com/issues/12156
https://github.com/canonical/ubuntu.com/issues/12155

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Pull request merged**
