### PR TITLE
Implement design changes for mobile view

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Implements changes detailed in the [figma design](https://www.figma.com/design/p0y7lHJ7edLIeSXM1qbpRZ/23.10-C.com-%26-U.com---Navigation?node-id=201-1141&t=bchIBIK4MQdnFMkx-0)

## QA

- Check that [the demo](https://canonical-com-1337.demos.haus/) matches the figma design
- Check links have appropriate on hover behavior
- Check all links are visible and work

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-13464

### CODE REVIEW

**Comment by britneywwc** [comment]
The tab for "Solutions" is showing "Partner programmes" and I see that in the design it is showing "Explore our solutions". Which one should be used?
Screenshot 2024-08-09 at 3 21 48 PM

**Comment by petesfrench** [comment]
@britneywwc Updated, thank you!

**Review by britneywwc — APPROVED** [review]
Great stuff, thanks!

**Comment by Sophie-32** [comment]
Screen Shot 2024-08-09 at 10 51 41 AM

Text is overlaying the images

**Comment by Sophie-32** [comment]
Screen Shot 2024-08-09 at 10 52 55 AM

fyi - its happening in both sections

**Comment by petesfrench** [comment]
@Sophie-32 fixed the overlapping issue. Can you take another look please

**Comment by Sophie-32** [comment]
- hover state is missing on the solutions 'case studies
- hover state is missing on the company 'company highlights'

**Comment by Sophie-32** [comment]
> * the demo
Screen Shot 2024-08-12 at 3 30 26 PM
 
I meant when I hover over the actual items, there's no hover state

**Comment by petesfrench** [comment]
@Sophie-32 ah I see now. I have updated it accordingly

**Pull request merged**
