### PR TITLE
Add departments overview to /careers

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Added departments overview to /careers
- Removed redundant "Find your team" section

**Note: Icons to come in future pr when available**
**Must be merged after https://github.com/canonical/canonical.com/pull/701**

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: https://canonical-com-720.demos.haus/careers
- See that the overview matches the design 
- See that links work as expected 

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-534

### CODE REVIEW

**Review by sowasred2012 — APPROVED** [review]
LGTM!

**Comment by marinacastejon** [comment]
LGTM! Ready for Visual design review.

**Comment by sowasred2012** [comment]
@Zoospora another one for design review if you have time please

**Comment by Zoospora** [comment]
I see quite a few different things, so I don't know if I'm comparing with the same design. 
Is this the final design you are working on or is there another one?

[https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=4563%3A8766&t=AQeCqJvqdsZ2GO5b-0](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=4563%3A8766&t=AQeCqJvqdsZ2GO5b-0)

Captura de pantalla 2022-12-13 105630

Confirm this to me if possible and as soon as I know I will give you feedback. Thank you!

**Comment by mtruj013** [comment]
Hi @Zoospora, thanks for reviewing this! That mock-up is not quite right, it was really only meant to highlight the departments overview changes, a lot of other stuff is out of date. The bottom "Find your team" section is not supposed to be there (the departments overview section is meant to replace it), the CTA buttons in "Remote working" and "Our mission" are also not supposed to be there (those pages haven't been built yet), and the icons for the departments overview section are still pending from the design agency. The decision was that we would move forward without them and add them in a follow up pr once available. Please let me know if that answers your question! 🙂

**Comment by Zoospora** [comment]
> Hi @Zoospora, thanks for reviewing this! That mock-up is not quite right, it was really only meant to highlight the departments overview changes, a lot of other stuff is out of date. The bottom "Find your team" section is not supposed to be there (the departments overview section is meant to replace it), the CTA buttons in "Remote working" and "Our mission" are also not supposed to be there (those pages haven't been built yet), and the icons for the departments overview section are still pending from the design agency. The decision was that we would move forward without them and add them in a follow up pr once available. Please let me know if that answers your question! 🙂

No problem at all! Thanks for the context because I didn't know what to compare it to. I'll take a look then and confirm!

**Comment by Zoospora** [comment]
LGTM! 😊

**Pull request merged**
