### PR TITLE
Redesign /partners/public-cloud

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Applied redesign as per [mock-up](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=9441-22394&t=xdbcdCibsjrniJS0-0)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: https://canonical-com-896.demos.haus/partners/public-cloud
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- See that the page matches design 

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-3744

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
Looks great, thanks @mtruj013. Could you please change the ticked list to the new divided version and it is good to go. Adding +1 for an easier merge once the list is updated.

**Comment by mtruj013** [comment]
Thanks all, updated! @juanruitina could you take a look?

**Comment by juanruitina** [comment]
Nice work! Some comments:

- [ ] AWS logo seems to be the old one ([this is the new one](https://assets.ubuntu.com/v1/83ff4203-awshp-strip-customers.png)), can you update it? Not sure which exact asset works best here.
- [ ] In "A selection of our public cloud partners", "Public Cloud" should be capitalised.
- [ ] On the last bullet point, please change "Ubuntu Advantage for Infrastructure" for "Ubuntu Pro", linking to https://ubuntu.com/pro.
- [ ] On mobile, the borders on the logo rows start at the left edge of the screen, I understand they should keep the same margin as every other block. Can you tweak this?

canonical-com-896 demos haus_partners_public-cloud(Figma mobile)

**Comment by ClementChaumel** [comment]
> Nice work! Some comments:
> 
> * [ ]  AWS logo seems to be the old one ([this is the new one](https://assets.ubuntu.com/v1/83ff4203-awshp-strip-customers.png)), can you update it? Not sure which exact asset works best here.

Again, we can't update logos without agreement from the PMs. Should they wish to do it, they can do it in the admin view

**Comment by mtruj013** [comment]
Thanks @juanruitina, could you take another look?

**Pull request merged**
