### PR TITLE
Update cookie policy to v3.6.3

### PR DESCRIPTION
**Pull request by samhotep**
## Done

- Updated the coookie policy to v3.6.3

## QA

- View the demo in an incognito web browser at: https://canonical-com-1236.demos.haus/
- **Before** accepting cookies, 
  - Open developer tools and in the console type in `dataLayer`
  - There should be a `{"consent", "default"}` object in the dataLayer
- **After** accepting cookies, 
  - There should be a `{"consent", "update"}` object in the dataLayer

### CODE REVIEW

**Comment by laszlokajtar** [comment]
hey @samhotep, i did a quick test and the results are much better, however, GTM still seems to load earlier than the default consent:

image
image

**Comment by lorumic** [comment]
> * **After** accepting cookies,
>   
>   * There should be a `{"consent", "update"}` object in the dataLayer

Is the object with "consent", "default" in it supposed to go away after accepting the cookies? It currently stays there, alongside the one with "consent", "update".

**Comment by samhotep** [comment]
> > * **After** accepting cookies,
> >   
> >   * There should be a `{"consent", "update"}` object in the dataLayer
> 
> Is the object with "consent", "default" in it supposed to go away after accepting the cookies? It currently stays there, alongside the one with "consent", "update".

Yeah it stays there by default

**Comment by laszlokajtar** [comment]
@samhotep another issue is that the update seems to somehow work in reverse way,
in another test, i only allowed essential cookies, which resulted in this update push:

`{"ad_storage":"granted","ad_user_data":"granted","ad_personalization":"granted","analytics_storage":"granted","functionality_storage":"denied","personalization_storage":"denied","security_storage":"granted"}`

**Comment by samhotep** [comment]
> @samhotep another issue is that the update seems to somehow work in reverse way, in another test, i only allowed essential cookies, which resulted in this update push:
> 
> `{"ad_storage":"granted","ad_user_data":"granted","ad_personalization":"granted","analytics_storage":"granted","functionality_storage":"denied","personalization_storage":"denied","security_storage":"granted"}`

This happens because the default object has all values denied, so any selection, even essential will cause some update since some values will be updated to `true`

**Comment by laszlokajtar** [comment]
> > @samhotep another issue is that the update seems to somehow work in reverse way, in another test, i only allowed essential cookies, which resulted in this update push:
> > `{"ad_storage":"granted","ad_user_data":"granted","ad_personalization":"granted","analytics_storage":"granted","functionality_storage":"denied","personalization_storage":"denied","security_storage":"granted"}`
> 
> This happens because the default object has all values denied, so any selection, even essential will cause some update since some values will be updated to `true`

my bad, wrong selection choice, sorry please discard!

**Review by akbarkz — APPROVED** [review]

**Comment by laszlokajtar** [comment]
@samhotep on this demo, GTM still loads first for me

**Comment by laszlokajtar** [comment]
> @samhotep on this demo, GTM still loads first for me

is it possible that 

cpNs.cookiePolicy();

doesn't return before GTM is loaded?

**Comment by samhotep** [comment]
> > @samhotep on this demo, GTM still loads first for me
> 
> is it possible that
> 
> cpNs.cookiePolicy();
> 
> doesn't push the required values into the dataLayer before GTM is loaded?

You're right, I've made the changes in the cookie policy, thanks!

**Pull request merged**
