### PR TITLE
Build /data/opensearch

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Built page as per [doc](https://docs.google.com/document/d/1nVdoKoPrXw8lsvHEtMichlPNfxYU9Uj1zmKowcUXQ_w/edit#heading=h.eto59uxtlv76) (no design for this one)

## QA

- View the site locally in your web browser at: https://canonical-com-1045.demos.haus/data/opensearch
- Check against doc
- Check against design](https://www.figma.com/file/17XOOU2kMgAW7CsRhGyu4Y/23.10-C.com---Data-Fabric?node-id=862%3A8828&mode=dev) some elements that were inconsistent with the rest of the pages have been changed to keep consistency.
- Check there are no errors on [Waves](https://wave.webaim.org/extension/)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-5881

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
- 2.5rem width / height of these logos (spark, kafka, opensearch, etc. - they shouldn't overshadow the site logo) - applies to all the pages using this format
- shallow space at top of the hero (applies to all the pages using this format)

image
 
this button should be in the p-section right above, same as on the previous pr:
image

(optional) I would put thew logos like so as they are too few:
image

**Comment by mtruj013** [comment]
Thanks @lyubomir-popov! Before I push those changes I wanted to ask about the use-cases section. I assume the same feedback applies for this section as it did on /mongodb is that correct? So it'd be changed to a 50/50 split like so: 
image

vs: 
image

If so, I assume the 2 surrounding sections should be changed to a 50/50 split as well right? Would look like this if my assumption is right: 
image

I'll wait for your confirmation before I push !

**Comment by juanruitina** [comment]
@mtruj013 The layout changes you suggest look good to me.

Some more feedback:

- Turn "Run OpenSearch on" into an H2 (keep the formatting)
- Please add alt text to the logos: Microsoft Azure, Kubernetes, OpenStack, VMware, Google Cloud, Amazon Web Services
- Remove the hyphenation in "OpenSearch enterprise use cases".
- Turn the bold items under "OpenSearch enterprise use cases" and "Services" into H3s
- Please move the CTA section above the resources, no white background, add the HR on top as we have been doing lately.
- Add the disclaimer below the resources.
- In line with [this](https://github.com/canonical/canonical.com/pull/1046#issuecomment-1733357512), please replace the OpenStack logo with the non-Canonical version.

**Comment by lyubomir-popov** [comment]
Yes please make them consistent as in the other reviews @mtruj013 

A couple of other small things:

All pages should have 1.5rem padding top at the top of the hero - shallow:
image

then 4rem padding-bottom (regular p-section for example):
image

- please make opensearch logo smaller - 2.5rem tall

**Comment by lyubomir-popov** [comment]
too much spacing here - 
image

should look like this:
image

wrong styling - should either use h2 or small caps
image

why deep sections here?
image

**Comment by carkod** [comment]
> * [ ]  Add alt text to all the logos: Microsoft Azure, Kubernetes, OpenStack, VMware, Google Cloud, AWS
> * [ ]  Make "OpenSearch enterprise use cases" an H2, keep the current styling.
> * [ ]  Under that, turn all bold headings ("Search", "Analytics and machine learning") into H3, keep the current styling.
> * [ ]  Under "Services", turn "Managed OpenSearch" and "Consulting" into H3, keep the current styling.
> * [x]  Get started with Charmed OpenSearch ›](https://ubuntu.com/data/docs/opensearch/iaas) should be a p element, keep the current styling.

mmm Are you sure about third point? Usually @lyubomir-popov wants the left title to be different from the ones on the right side?

**Comment by juanruitina** [comment]
> > * [ ]   Add alt text to all the logos: Microsoft Azure, Kubernetes, OpenStack, VMware, Google Cloud, AWS
> > * [ ]   Make "OpenSearch enterprise use cases" an H2, keep the current styling.
> > * [ ]   Under that, turn all bold headings ("Search", "Analytics and machine learning") into H3, keep the current styling.
> > * [ ]   Under "Services", turn "Managed OpenSearch" and "Consulting" into H3, keep the current styling.
> > * [x]   Get started with Charmed OpenSearch ›](https://ubuntu.com/data/docs/opensearch/iaas) should be a p element, keep the current styling.
> 
> mmm Are you sure about third point? Usually @lyubomir-popov wants the left title to be different from the ones on the right side?

This is just about the accessibility tree. All the headings in the page look correct and should stay the same, I'm just referring to the heading element to use.

**Comment by carkod** [comment]
Done. I followed the design that @lyubomir-popov showed in the call, but I used the elements that were consistent in the other pages.

**Comment by juanruitina** [comment]
> * [x]  Get started with Charmed OpenSearch ›](https://ubuntu.com/data/docs/opensearch/iaas) should be a p element, keep the current styling.

Minor thing: this is not fixed yet. +1ing this to make things smoother. Page looks great btw.

**Review by carkod — APPROVED** [review]

**Pull request merged**
