### PR TITLE
on candidate withdrawal send email to hiring lead - WD-2917 

### PR DESCRIPTION
**Pull request by muhammadbassiony**
## Done

When a candidate withdraws send email to notify the hiring lead(s)

## QA

- go to a candidate's application page
- withdraw the application
- at the end you should see a debug email that should be sent to the hiring lead (emails cannot be sent locally)

### CODE REVIEW

**Comment by muhammadbassiony** [comment]
Can you check this? @anthonydillon

**Comment by muhammadbassiony** [comment]
Can you check this? @anthonydillon 
we cant test sending an email in local testing

**Comment by mtruj013** [comment]
@anthonydillon could you take a look when you can?

**Review by anthonydillon — CHANGES_REQUESTED** [review]
The description on this PR could be much better. The QA steps are lacking. I have tested it on the demo and it 500s. Please try using [this candidate](https://pastebin.canonical.com/p/BpxqxVTQPQ/) when QA'ing.

**Review by anthonydillon — APPROVED** [review]
Code and QA LGTM but would like to test in production once live.

**Pull request merged**
