### PR TITLE
Update favicons

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Updated favicons as per request

Note: It is still not clear to me which asset is the correct replacement for a given favicon.  

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- See that the favicons have been updated

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-4615

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
@mtruj013 I think we should merge this and then see if we ca nmake the icon a little less lburry. It seems to me that it hasn't been optimised for that small size. But since the design work on this was handled externally, I would relay those comments to the person doing the work. 

Separately, from my short research, I think we need a .manifest icon for android, and a 180px square icon for iOS, not the 144 provided here, but I'm not an expert. Maybe we should inquire what guidelines the designer used and check whether those are the latest recommendations. Either way, I think this is ok to go in as is in the interest of delivering this project. Further optimisations can happen later.

**Comment by anthonydillon** [comment]
Why has this got an old commit of mine in it?

**Review by anthonydillon — CHANGES_REQUESTED** [review]
See above

**Comment by mtruj013** [comment]
@anthonydillon I have absolutely no idea. Maybe I messed something up when rebasing?

**Comment by mtruj013** [comment]
Reverting the last 3 commits ended up making an even bigger mess. Still not sure how this happened in the first place, but I've moved these changes to https://github.com/canonical/canonical.com/pull/925, closing this one.  cc: @anthonydillon

**Pull request closed without merging**
