### PR TITLE
WD-7800 - adjust job search field

### LINKED ISSUE #981: Careers search is too strict
The search functionality on https://canonical.com/careers does not return results that should be returned.

### Setup
Given two roles with the following titles:
- Software Engineer - Ubuntu Build Infrastructure
- Software Engineering Manager - Ubuntu Build Infrastructure

### Steps to reproduce
1. Visit https://canonical.com/careers
2. Type "ubuntu", "build", "infrastructure", "ubuntu build", "build infrastructure", or "ubuntu build infrastructure" into the search box
3. Select "Search roles"

### Expected behaviour
- Search results for the provided search term are displayed.
- Both the roles listed in the "Setup" section are part of the search results.

### Actual behaviour
- Search results for the provided search term are displayed.
- Only one role is part of the search results.

### Additional notes
- Investigation highlighted that `fuse.js` is used for the search, and it checks `title`. `description`, `departments`, and `skills` fields, with `threshold = 0.3`.
- In a prototype, I've tested that `threshold = 0.7` returns the results that were previously missing, but of course there are many more other results that are also returned.
- One suggestion is to use the `ignoreLocation` parameter with e.g. `ignoreLocation = true`, so that the entire text is eligible for search
- Another suggestion is to update `threshold = 0.7`.
- Yet another suggestion is to add tags functionality that can be used for searching
- A final suggestion is to create a list of all words in both the title and description, remove certain common words that shouldn't be searchable ("the", "in", "and", etc), and then add this list to the searchable keys.

### PR DESCRIPTION
**Pull request by lizzochek**
## Done

Updated job search field to give wider range of results and sorted them by relevance

## QA

- [demo link](https://canonical-com-1150.demos.haus/careers)
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the job search matches expected results

## Issue / Card
[WD-7800](https://warthogs.atlassian.net/browse/WD-7800)

Fixes #981

## Screenshots

[WD-7800]: https://warthogs.atlassian.net/browse/WD-7800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by juanruitina** [comment]
Super nice work, Liza. Even if the job offers mentioned in #981 don't seem to be available anymore, search is throwing more and better results, sorted by relevance (e.g. title takes precedence over description, etc.). It seems a good fix to me, weighting was the way to go. I'm also glad it's naturally bringing up the "fast track" job offers, e.g. "Python Engineer" is now listed first when searching "python".

The only thing left to do is to adjust the search suggestions to match the results (see below). Can you do it? Happy to +1 this if you would rather handle it in a separate issue.

Screenshot 2024-01-02 at 08 49 50

**Comment by lizzochek** [comment]
@juanruitina as I'm quite free now, I can fix it in this issue, not sure whether @akbarkz would want it in a separate issue.

**Comment by juanruitina** [comment]
@lizzochek Perfect, I'd prefer to launch this all at once.

**Comment by lizzochek** [comment]
@juanruitina autofill updated

**Review by akbarkz — APPROVED** [review]

**Comment by juanruitina** [comment]
Brilliant, Liza, UX+1.

**Pull request merged**
