### PR TITLE
Enable the fast track links

### PR DESCRIPTION
**Pull request by anthonydillon**
Demo

## Do not merge

### CODE REVIEW

**Comment by gerwitz** [comment]
Mark and Hanna asked for a design review and chose "[Option 2](https://www.figma.com/file/c4QYGBPZl5hxr5XrziIVZA/23.10-C.com---careers%2Fengineering?type=design&node-id=51-5605&mode=design)" prepared by @juanruitina and @Sophie-32

**Comment by carkod** [comment]
Should we close this now? It is completed in https://github.com/canonical/canonical.com/pull/1094?

**Comment by juanruitina** [comment]
Yes! Closing this.

Duplicate of #1094

**Comment by juanruitina** [comment]
Duplicate of #1094

**Pull request closed without merging**
