### PR TITLE
Redesign /partners/iot-device

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Applied redesign as per [mock-up](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=8687-24645&t=NcEDX6Dr5rSrJruV-0) 

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: https://canonical-com-897.demos.haus/partners/iot-device
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- See that the pages matches design

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-3741

### CODE REVIEW

**Comment by mtruj013** [comment]
@lyubomir-popov this is probably blocked on the Elektrobit logo, but regardless a few questions: I made some guesses as to what this is supposed to look like on smaller screens, but I'm not sure how to handle the logo section on medium screens (50/50?). Could you also give some guidance regarding the Ubuntu Certified logo? I've never seen this pattern before and I've no idea what best practice is here. Thanks!

**Review by ClementChaumel — APPROVED** [review]
LGMT

**Comment by mtruj013** [comment]
@lyubomir-popov @juanruitina could you both please take a look at this?

**Comment by lyubomir-popov** [comment]
Hi @mtruj013 looks good, a few small issues:

image

on large screens, the link should be in a column with col-start-large-7 


image
The paragraph text can take one more column at the medium breakpoint, would be more readable.

And 3 of the logos need updating, @egezeytun can Julia or Camille help? If not I'll do it after the end of the pro sprint

**Comment by juanruitina** [comment]
Only one thing on my side: we should use the [new Ubuntu Certified tag](https://assets.ubuntu.com/v1/f76dd871-ubuntu-certified.png). Can you replace it? Also, please add the slight margin on top of it. Other than that, LGTM.

**Comment by mtruj013** [comment]
Thanks @lyubomir-popov and @juanruitina, updated. Could you take another look and update your respective labels if you're happy with the changes? Thanks.

**Comment by lyubomir-popov** [comment]
All but the logos looks good, thanks @mtruj013. Let's do the logo fixes on a separate PR once everything is in the feature branch. Giving +1 here.

**Pull request merged**
