### PR TITLE
Update application profile pages with new layout

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

**Don't merge** wait for this to be merged: https://github.com/canonical/canonical.com/pull/654/files

Update application profile pages with new layout based on the layout described in [the spec](https://docs.google.com/document/d/1aENPmLdPjoRtMgmmGX2x4iewevRv905OdkKgqqm-sHk/edit#bookmark=id.4c2wishvowu8), please reach out if anything isn't clear

## QA

- Run this branch with the appropriate env keys
- Check out the demo with people in the two different stages we account for, Application review and  Assessment+

## Issue / Card

Fixes https://github.com/canonical/canonical.com/issues/645

### CODE REVIEW

**Comment by petesfrench** [comment]
@marinacastejon can you take a look at this and make sure it is correct please

**Comment by marinacastejon** [comment]
Hi @petesfrench when the demo URLs are ready for QA please send me all the use cases if possible. From the [specs](https://docs.google.com/document/d/1aENPmLdPjoRtMgmmGX2x4iewevRv905OdkKgqqm-sHk/edit#bookmark=id.4c2wishvowu8), there should be 6 cases for me to review (1 case in State A and 5 cases in State B), thanks!

**Comment by sowasred2012** [comment]
@lyubomir-popov @anthonydillon is the work in this PR still relevant, can any of it be used?

**Comment by lyubomir-popov** [comment]
@sowasred2012 not sure - the best thing to do would be to check the current version against the spec, as @anthonydillon has done a lot of changes on another branch which will probably cause conflicts.

**Comment by anthonydillon** [comment]
I believe everything was captured in the end in the other branch. @petesfrench were there any distinct features added to this PR or is it just layout?

**Comment by petesfrench** [comment]
@anthonydillon The change in this PR were just to the layout, which appears to be fully addressed in Lyubo's PR

**Comment by sowasred2012** [comment]
@petesfrench we can just close this PR, no need to delete.

**Pull request closed without merging**
