### PR TITLE
Update to vanilla-4.0-alpha

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Updates to vanilla-4.0-alpha

## QA

- Check that nothing is broken by upgrading to vanilla-4.0

### CODE REVIEW

**Review by mtruj013 — COMMENTED** [review]
LGTM, only weirdness I've noticed is the logo sizes seem to have changed? They're bigger now which maybe is fine but Liquid PC logo on the [/partners/channel-and-reseller](https://canonical-com-854.demos.haus/partners/channel-and-reseller) page looks a bit too large 
image
Not sure if it's just me though or even if it's a legitimate design issue. WDYT @lyubomir-popov ?

**Comment by lyubomir-popov** [comment]
Yes, the logos need to be resized according to the logo template. 
Maybe something we can outsource to Lorena @egezeytun?

**Comment by egezeytun** [comment]
> Yes, the logos need to be resized according to the logo template. Maybe something we can outsource to Lorena @egezeytun?

Jira issue here: https://warthogs.atlassian.net/browse/DES-410

**Comment by petesfrench** [comment]
@egezeytun I have made an issue in sites maintenance https://warthogs.atlassian.net/browse/WD-3651

**Comment by egezeytun** [comment]
> @egezeytun I have made an issue in sites maintenance https://warthogs.atlassian.net/browse/WD-3651

Thanks Pete! Linking them.

**Comment by lyubomir-popov** [comment]
Is the hairline line under the suru something we introduced in this pr?

image

If so, can we please swap that suru for the one [here](https://ubuntu.com/pricing/pro)?
preview:
image

**Comment by petesfrench** [comment]
@lyubomir-popov no, that is a bug that has existed as long as those suru. 
Could the logos issue not be fixed within vanilla? If this is something that is going to affect all logos, wouldn't it be simpler to fix it at the source.

**Comment by lyubomir-popov** [comment]
> Could the logos issue not be fixed within vanilla? If this is something that is going to affect all logos, wouldn't it be simpler to fix it at the source.

The logos need to be resized so they are visually balanced, this is photoshop work that we do internally or outsource. The css in vanilla is already doing the rest.

**Comment by lyubomir-popov** [comment]
@petesfrench can we revert the font-weight on this to be thin? 
image

**Comment by lyubomir-popov** [comment]
Other than the above, things look good to me - I think we're safe to merge this. What do you think @bartaz?

**Comment by petesfrench** [comment]
@lyubomir-popov Done. I have also ran 'format-prettier' in case you are wondering why there are so many file changes. Seems it was a little overdue

**Comment by bartaz** [comment]
With wider grid the blog cards are wider as well, but it seems that images don't scale up:

image

**Comment by lyubomir-popov** [comment]
@petesfrench yes, gave QA +1

**Comment by petesfrench** [comment]
@lyubomir-popov Can you approve the PR please

**Review by lyubomir-popov — APPROVED** [review]
LGTM.

**Pull request merged**
