### PR TITLE
copy update: /careers/company-culture

### PR DESCRIPTION
**Pull request by jasmine-canonical**
## Done

- Updates /careers/company-culture to changes some numbers and switch from British to American English

## QA

- View the site locally in your web browser at: https://canonical-com-1461.demos.haus/careers/company-culture
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that /careers/company-culture matches the [copy doc](https://docs.google.com/document/d/1PAeP_ZO4JzSBCi-fRp6F7SYtSSRY-4DcWLUf9HJaMxs/edit?usp=sharing)

## Issue / Card

Fixes [WD-17731](https://warthogs.atlassian.net/browse/WD-17731)

[WD-17731]: https://warthogs.atlassian.net/browse/WD-17731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jasmine-canonical** [comment]
I noticed that the changes made to switch from British to American English were inconsistent (ex. some of the "organisation" words were changed to "organization" while others were left as is). Please let me know if you'd like for me to change those as well, or if that'll be left for a different copy update.

**Comment by fasih-mehmood** [comment]
> I noticed that the changes made to switch from British to American English were inconsistent (ex. some of the "organisation" words were changed to "organization" while others were left as is). Please let me know if you'd like for me to change those as well, or if that'll be left for a different copy update.

^ @akbarkz

**Comment by fasih-mehmood** [comment]
> I noticed that the changes made to switch from British to American English were inconsistent (ex. some of the "organisation" words were changed to "organization" while others were left as is). Please let me know if you'd like for me to change those as well, or if that'll be left for a different copy update.

I believe these should be replaced as well. I've added comments in the copy doc and tagged you @jasmine-canonical, so lets hold off on merging this until Gloria responds.

Thank you!

**Review by fasih-mehmood — APPROVED** [review]

**Comment by jasmine-canonical** [comment]
> I believe these should be replaced as well. 

@fasih-mehmood the additional changes have been included! Please let me know if it's ok to merge now.

**Pull request merged**
