### PR TITLE
WD-909 New career explorer

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Applied game redesign 

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: https://canonical-com-794.demos.haus/careers/career-explorer
- Check functionality 
- Check against design, below:
image-20230119-172730

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-909

### CODE REVIEW

**Comment by anthonydillon** [comment]
@mtruj013 @lyubomir-popov could you try out the demo? I only have the modal left to implement but I am wondering if the awkward user experience and a11y issues are worth it. Try it out and see if you think it works okay without a description of the skill.

**Comment by lyubomir-popov** [comment]
My personal opinion is that this is not an ideal way to do this, and I had an alternative design here https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=7089%3A18927&t=XGS5MbHdu18Qgq2o-1 that tried to address some of the awkward interaction, by turning it into a simple form with checkboxes... However this was rejected in Design Assembly. 

The alternative design (still not ideal, but I feel a little less awkward):
image

**Comment by anthonydillon** [comment]
The only thing missing from the demo is the modal to show the extended description. I assume from the design. If a user clicks anywhere in other than directly on and small check boxes it will open the modal which breaks form labelling. In my opinion, there is enough information already displayed to make a choice.

I'll rewatch the design assembly for context.

**Comment by lyubomir-popov** [comment]
@anthonydillon Here's the DA relevant recordin, skip to minute 34: https://drive.google.com/file/d/1MsJ1uhxAP_KOx2pX4MGkfzwF8rYPmL_0/view

**Comment by anthonydillon** [comment]
Didn't sound like anyone was against dropping the description and I would suggest the addition of the modal causes issues which outweigh the need to further description the skills.

**Comment by lyubomir-popov** [comment]
@anthonydillon that's something to confirm with @gloriaquintanilla, I personally don't mind omitting the modal. 

Two more things: 

- there's an extra space between word and comma:

image

- either the whole highlighted area of the cards should be clickable, or only the checkbox - having the text clickable but the empty areas not seems a little confusing to me.

**Comment by anthonydillon** [comment]
@marinacastejon could you play with the demo and let me know if we need the description.

**Comment by marinacastejon** [comment]
> demo and let me know if we need the description

LGTM, I agree with dropping the description 👍

**Review by mtruj013 — COMMENTED** [review]
This looks awesome!! Two minor things: for smaller screens the filled out skills section seems to break the grid a little bit 
Screenshot from 2023-03-22 19-27-58

For medium screens, not sure if this is necessarily an issue, but when they've only selected 4 skills the last empty line takes up the entire remaining width
Screenshot from 2023-03-22 19-27-32

**Comment by anthonydillon** [comment]
Thanks @mtruj013 I got my min max the wrong way round. Could you try it now?

**Review by anthonydillon — APPROVED** [review]

**Pull request merged**
