### PR TITLE
[copy update] WD-5625 Update executive summit events

### PR DESCRIPTION
**Pull request by pedoch**
## Done

- Update summit even dates and links
- Move the Paris Summit to the past events section

## QA

- Check out [the demo here](https://canonical-com-1009.demos.haus/partners/executive-summit) and compare it with the changes requested in [the copy doc](https://docs.google.com/document/d/15C3k-htvapwp-WTrYQ2SdHBW20Lp9IinpY9mkvo6q3U/edit).

## Issue / Card

- [WD-5625](https://warthogs.atlassian.net/browse/WD-5625)

[WD-5625]: https://warthogs.atlassian.net/browse/WD-5625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pedoch** [comment]
Hey @petesfrench, please could you take a look at this PR if you've got the time?

**Review by petesfrench — APPROVED** [review]
LGTM

**Comment by lyubomir-popov** [comment]
looks good. only one thing, the space above the images is too big. Are they using .p-image-wrapper?

**Comment by pedoch** [comment]
@lyubomir-popov I think this page was built before that class was made available. I'll add it to the images now.

**Comment by pedoch** [comment]
@lyubomir-popov it seems there was an extra `margin-top` was added to the `p-image--wrapper` class (probably needed in other pages) which wasn't there initially. I have added the `u-no-margin--top` class to the image wrapper on this page now so everything should look good. Let me know what you think.

**Comment by lyubomir-popov** [comment]
@pedoch the margin top is the point of having p-image-wrapper:) dont override it, remove anything else adding extra space on top of the images. you should have class p-rule on all hrs, that removed their margin bottom

**Comment by pedoch** [comment]
@lyubomir-popov all hrs have the `p-rule` class. The `p-image--wrapper` class has both `margin-top` and `padding-top` properties. So I guess I'll override the the `padding-top` instead.

**Comment by lyubomir-popov** [comment]
@pedoch please just delete the margin-top. I've seen this bug elsewhere, not sure when it got introduced - it wasn't the case when we made the rebranding live. Don't override it, please fix the source of the problem by removing that rule from p-image-wrapper.

**Comment by pedoch** [comment]
@lyubomir-popov okay I'll remove it. DIdn't want to touch the class since it was being used in other pages, and wasn't sure if that was on purpose or not.

**Comment by pedoch** [comment]
@lyubomir-popov I have removed it from the `p-image--wrapper` class, you can take a look now

**Comment by lyubomir-popov** [comment]
Thanks a lot @pedoch ! LGTM.

**Pull request merged**
