### PR TITLE
WD-3107 build new executive summit page

### PR DESCRIPTION
**Pull request by pedoch**
## Done

- Build the new executive summit page

## QA

- Check out the [demo here](https://canonical-com-865.demos.haus/partners/executive-summit) and compare it with the [copy doc](https://docs.google.com/document/d/15C3k-htvapwp-WTrYQ2SdHBW20Lp9IinpY9mkvo6q3U/edit) and the [design](https://www.figma.com/file/6wmLn4OgDDAgfpmkLFqfp5/c.com%2Fpartners%2Fexecutive-summit?node-id=0%3A1&t=0PNCjIEAdjiJfmKb-1).

## Issue / Card

- [WD-3107](https://warthogs.atlassian.net/browse/WD-3107)

[WD-3107]: https://warthogs.atlassian.net/browse/WD-3107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by carkod** [comment]
@lyubomir-popov @juanruitina can you guys take a look when you can?

**Comment by juanruitina** [comment]
Hi Ochuko, this looks good. Some minor tweaks:

* Can you please link the "Paris" heading to the [Engage page](https://ubuntu.com/engage/canonical-executive-summit-paris-2023) as well? I reflected this change on the copy doc.
* Can you add " for Executive Summit Paris" only for screen readers after "Register" in the button label?
* The meta description Felipe provided is too long. I've asked him to revisit it in the copy doc.

Thank you!

**Comment by lyubomir-popov** [comment]
lyubomir-popov
[1:21 PM](https://chat.canonical.com/canonical/pl/czei1ppncprs5fasssbaxydkgy)
@deltanboi for the summit page, just pushed my QA as a commit on your branch 

what's left there: a) replicate what I did on the Paris item (responsive improvements basically) onto all other cities;  and b) propose the p-image-wrapper class/ example to vanilla (not strictly necessary, but would be nice if you have a minute)

**Comment by pedoch** [comment]
@juanruitina I've implemented your UX suggestions, could you take a look please.

**Comment by juanruitina** [comment]
Looks good! I +1'd it.

**Comment by lyubomir-popov** [comment]
Please do a 50% split on the medium breakpoint for all sections, including:
image

The images don't seem to be 2x3, can you please update vthe calculation?

For the CTAs at the bottom, can you please:
- wrap the heading in a p-block
- insert 3 empty columns (`col-start-large-4 col-start-medium-3`)
- turn the long button into a link, it is too long for a button

preview:
image

**Comment by pedoch** [comment]
@lyubomir-popov I've addressed your comment, could you please take another look?

**Review by mtruj013 — APPROVED** [review]
This looks awesome @pedoch, great job! Return link 404s after form submission but that's just because it has the base URL and the page isn't live yet, so all good 👍🏻

**Comment by lyubomir-popov** [comment]
@pedoch looks great, just one comment - can you please make these 2 appear on one line:

image

**Comment by pedoch** [comment]
@lyubomir-popov it's done. Please take a look.

**Comment by lyubomir-popov** [comment]
Almost there, but maybe drop on two lines when it gets to this point? 
image

**Comment by pedoch** [comment]
@lyubomir-popov please check again

**Comment by lyubomir-popov** [comment]
your grid is broken:

image
image

**Comment by lyubomir-popov** [comment]
@pedoch this is still broken: 
image

**Comment by pedoch** [comment]
@lyubomir-popov done

**Pull request merged**
