### PR TITLE
Apply nav updates

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Added fade functionality when nav item is open
- Added /projects to company bubble
- Reinstated products link in nav

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: https://canonical-com-953.demos.haus/
- See that the requested changes have been made

## Issue / Card

Fixes # https://warthogs.atlassian.net/browse/WD-4977

### CODE REVIEW

**Comment by mtruj013** [comment]
@lyubomir-popov this ticket was meant to also address this comment:
image

However I ended up skipping it since it is actually aligned, you just don't see it until you hover:

image

Please confirm if that's correct

**Comment by ClementChaumel** [comment]
A few QA issues: 

- [ ] It doesn't go away if you close the dropdown by clicking it again
- [ ] it's only overlaying the top of the page so it's hidden if you scroll down (should be fixed)
- [ ] Maybe out of scope but you can't close the nav by pressing escape
- [ ] It appears on mobile as well even though I don't think it's necessary since the content don't overlap here.

**Comment by lyubomir-popov** [comment]
Looks good, please only make the fade more pronounced, like opacity 0.08 instead of 0.5:
image

**Comment by mtruj013** [comment]
@lyubomir-popov done!

**Comment by lyubomir-popov** [comment]
+1, thanks @mtruj013 !

**Pull request merged**
