### PR TITLE
/partners redesign 

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Added Silicon section to the partners page ([doc](https://docs.google.com/document/d/1q6dkqQ0zcshrfOmdJA_bAip73EaMSEyXAn8bAD7GqNw/edit#heading=h.c32qy927hx83) out of date, please check against existing page)
- Applied redesign as per [mock up](https://www.figma.com/file/a84HnjH4M3E8KErVkPq9eW/Canonical.com%2Fpartners?node-id=1-1147&t=DeygTIESmpYEySFR-0)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: https://canonical-com-839.demos.haus/partners
- See that the requested changes were made (Only already live partners and Silicon should be on the page, please ignore the rest of the partners on the doc)
- See that the page matches desgin 

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-3124

### CODE REVIEW

**Comment by camillet16** [comment]
@mtruj013 Ah! 🎉  Suru is not janking up that is awesome!!! Thanks for the awesome work! Here are some feedbacks. Just padding and `<hr>` stuff. Looking great!

Screen Shot 2023-04-19 at 5 44 58 PM


-----

Screen Shot 2023-04-19 at 5 46 44 PM

- padding-bottom:0  on the 'LOGIN' section. The 'PROGRAMMES' section already has a 64px padding-top so the whitespace gets bigger.

- `<hr>` missing on top of each child of 'PROGRAMMES'
------
Screen Shot 2023-04-19 at 5 53 45 PM

- There is a lot of missing content?  did the copy doc change?

**Comment by mtruj013** [comment]
Thanks @camillet16! I've addressed your comments if you could take another look? The copy doc didn't change, it's just wildly out of date. I double checked with @juanruitina  before putting this up for review and he told me to only include the partners that were already live (plus Silicon of course)

**Comment by carkod** [comment]
This is up to design but there is a cut off point here in the background image
Screenshot from 2023-04-20 10-05-08

**Review by carkod — APPROVED** [review]
LGTM

**Comment by camillet16** [comment]
@mtruj013 Looks great! just one thing then the +1 is yours for the taking.

can we remove the padding-bottom for the login section? das it.

Screen Shot 2023-04-20 at 12 48 26 PM

**Comment by lyubomir-popov** [comment]
Hi there's a few things to fix here, let me commit directly it will be faster. Please don't merge.

**Comment by lyubomir-popov** [comment]
partial fixes  we discussed in or meeting:
https://pastebin.canonical.com/p/vKXTBYsydT/

I still need to push a fix for the vsuru and some layout improvements, will do so by Monday

**Comment by mtruj013** [comment]
@lyubomir-popov pushed the updates for medium screens, please pull before you push the changes to the suru

**Comment by mtruj013** [comment]
Did a final code/qa for the changes @lyubomir-popov pushed, got design +1 via MM, merging

**Pull request merged**
