### PR TITLE
WD-3173 Build remote work

### PR DESCRIPTION
**Pull request by carkod**
## Done

Remote work page according to [design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=8688-24647&t=EGOqx7V8m0IR1qWa-0)

## QA

- Check https://canonical-com-876.demos.haus/careers/company-culture/remote-work with [design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=8688-24647&t=EGOqx7V8m0IR1qWa-0)
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-3173
Closes https://warthogs.atlassian.net/browse/WD-3177

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
QA here

**Comment by lyubomir-popov** [comment]
QA in figma 
image
https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=8687%3A24645&t=EY6e3j0xByE34zGl-1

**Comment by marinacastejon** [comment]
LGTM Thanks @carkod

**Comment by carkod** [comment]
> Looks good, only one thing - this needs col-start-medium-4 image

Done

**Review by tbille — APPROVED** [review]
LGTM

**Pull request merged**
