### PR TITLE
Improve layout of candidate page

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

Improve layout of candidate page
## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by anthonydillon** [comment]
I know I said I would get to this but I was swapped today and I'm off for two days now. Would someone mind working on this with @marinacastejon in my absence?

**Comment by lyubomir-popov** [comment]
Please remember to turn the role in the top section into a link.

**Comment by sowasred2012** [comment]
@lyubomir-popov is there an issue/list of things that need updating that we can work from?

**Comment by lyubomir-popov** [comment]
@sowasred2012 don't think so, this just needs to be reviewed and merged, with the role turned into a link.

**Comment by petesfrench** [comment]
@lyubomir-popov Is this addressing the same thing as in this PR?: https://github.com/canonical/canonical.com/pull/670

**Comment by lyubomir-popov** [comment]
no, this is finessing various things. there might be partial overlap but needs to go in first

**Comment by petesfrench** [comment]
It doesn't look quite right for a candidate in the 'Application review' stage:
image
As well for other application stages on smaller screens:
image

**Comment by lyubomir-popov** [comment]
Well spotted @petesfrench I'll work on it.

**Review by petesfrench — APPROVED** [review]

**Comment by carkod** [comment]
@lyubomir-popov any updates on this?

**Comment by lyubomir-popov** [comment]
@anthonydillon looks great, just that pesky tick.

Currently:

image


Ideally:

image

**Comment by anthonydillon** [comment]
@marinacastejon 

Case 1: Name only
image


Case 2: Video only
image


Case 3: Video + bio
image


Case 4: Photo + bio
image


Case 5: Photo + bio + video
image

**Comment by anthonydillon** [comment]
@lyubomir-popov Updated the icons to match the design.

**Comment by lyubomir-popov** [comment]
Sorry I think  ididn't makle myself clear - the overal circles should stay as they were - it's just that the tick squigle needs to be at 16px, and we can't use the outlined version of   the icon - it is too thick, compare to the number 3 outline for example.

So it needs to be the old sized bigger circel, 16px tick icon in the center, 1px outline as in the number 3.

Also, in the Richard Kim screenshot above, the top padding of the suru strip is missing in a few of the screenshots - I think it's that logic which substitutes sections depending on what goes in the header, some of the sections must have a u-no-padding--top.

**Comment by sowasred2012** [comment]
@marinacastejon to do QA when this is ready

**Comment by anthonydillon** [comment]
@marinacastejon done, 
image

**Review by steverydz — APPROVED** [review]
LGTM 👍

**Comment by marinacastejon** [comment]
LGTM

**Pull request merged**
